server:
  port: ${port:10086}
spring:
  application:
    name: abcdefg
eureka:
  client:
    service-url:
      defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka}
#    register-with-eureka: false
#    fetch-registry: false